# Dockerfile_fragment_current_post START

# RUN wget -v https://repo.anaconda.com/miniconda/Miniconda3-py38_4.12.0-Linux-x86_64.sh -O /tmp/miniconda.sh && \
#     sudo mkdir -p /opt/conda && \
#     sudo chown -R "stuser:stuser" /opt/conda && \
#     bash /tmp/miniconda.sh -bup /opt/conda

# RUN eval "$(/opt/conda/bin/conda shell.bash hook)" && \
#     conda init 
    
# Dockerfile_fragment_current_post END
