#!/bin/bash
export "DOCKER_IMAGE_NAME=afzalex/fz-survival-tool"

rm -rf built
docker rm -f fzst

version="$(cat src/version.txt)"
ls -d src/*/ | while read tagdir; do

    printf "\033[1;32mBuilding for '${tagdir}' \033[0m\n"
    pushd .
    cd $tagdir
    tag=${PWD##*/}
    ./build
    pwd
    popd
    pushd .
    cd "built/$tag"

    printf "\033[1;32mPre-cleaning \033[0m\n"
    docker image rm -f "${DOCKER_IMAGE_NAME}:$tag"
    docker container rm -f "${DOCKER_IMAGE_NAME}:$tag"
    docker image rm -f "${DOCKER_IMAGE_NAME}:$version-$tag"
    docker container rm -f "${DOCKER_IMAGE_NAME}:$version-$tag"
    printf "\033[1;32mBuilding docker image \033[0m\n"
    docker build \
        --tag "${DOCKER_IMAGE_NAME}:$tag" \
        --tag "${DOCKER_IMAGE_NAME}:$version-$tag" \
        .
    popd
done

docker tag "${DOCKER_IMAGE_NAME}:full" "${DOCKER_IMAGE_NAME}:latest"
docker tag "${DOCKER_IMAGE_NAME}:full" "${DOCKER_IMAGE_NAME}:$version"


