# Dockerfile_fragment_current_pre START
RUN apt-get install -y "ffmpeg=7:4.3.4-0+deb11u1" 
# RUN apt-get install -y "unoconv=0.7-2"


RUN apt-get install -y "youtube-dl=2021.06.06-1" 
RUN apt-get install -y "libreoffice=1:7.0.4-4+deb11u3" 

# Dockerfile_fragment_current_pre END
